SWITCH_DISTANCE_TO_LEADER = 0.2             # radius of catch by leader
SWITCH_DISTANCE_TO_OTHER_PEDESTRIAN = 0.1   # SWITCH_DISTANCE_TO_LEADER
SWITCH_DISTANCE_TO_EXIT   = 0.4
SWITCH_DISTANCE_TO_ESCAPE = 0.01
