program: run_scripts_jax/run_training.py
name: sweep_grid_demo
method: grid
metric:
  goal: minimize
  name: episode_length
parameters:
  lr:
    values: [0.0001,0.001] #, 0.01, 0.1]
  num_minibatches:
    values: [32, 64] #, 128]
  gamma:
    values: [0.9, 0.92] #, 0.94, 0.96, 0.98]


